- cypress/test/main/mapper/mapper-component.spec.ts
- cypress/utils/selectors/mapper-component.selectors.ts
- src/app/main/mapper/cell/cell.component.html
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/iteration/iteration.component.html
- src/app/main/mapper/iteration/iteration.component.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.scss
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.spec.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/main/mapper/mapper.component.html
- src/app/main/mapper/mapper.module.ts
- src/app/models/iri-impl.ts
- src/app/models/language.ts
- src/app/models/mapping-base.ts
- src/app/models/mapping-details.ts
- src/app/models/property-mapping-impl.ts
- src/app/models/simple-iri-value-mapping-impl.ts
- src/app/models/subject-mapping-impl.ts
- src/app/models/triple.ts
- src/app/models/value-mapping-impl.ts
- src/app/services/model-management.service.ts
- src/app/utils/constants.ts
- src/app/utils/helper.ts
- src/assets/i18n/en.json
Provides Factory pattern to operate with concrete objects without exposing the logic behind, using an interface.
Does update properties of a single mapping. Do not support type changes.
> GDB-4546 Provides popup to update single cell

- src/app/main/mapper/cell/cell.component.html
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/iteration/iteration.component.html
- src/app/main/mapper/iteration/iteration.component.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.spec.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/main/mapper/mapper.component.html
- src/app/main/mapper/mapper.module.ts
- src/app/main/mapper/sources/source.component.html
Provides drag and drop functionality on mapper cells.
Provides column names autocomplete while typing.
> GDB-4603 Edit cells by dragging columns from the header

- src/app/app.module.ts
- src/app/main/mapper/iteration/iteration.component.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/main/mapper/mapper.component.html
- src/app/main/mapper/mapper.component.scss
- src/app/main/mapper/mapper.component.spec.ts
- src/app/main/mapper/mapper.component.ts
- src/app/main/mapper/mapper.module.ts
- src/app/utils/constants.ts
Add simple chimp control to manage namespaces.
Add namespaces auto completion on all prefix transformation fields.
> GDB-4545 Namespaces management and autocompletion

- src/app/main/mapper/header/header.component.html
- src/app/main/mapper/header/header.component.ts
- src/app/main/mapper/mapper.component.html
- src/app/main/mapper/mapper.component.ts
- src/app/services/rest/mapper.service.ts
- src/assets/i18n/en.json
Add link to the SPARQL editor with generated SPARQL query from API
> GDB-4542 Link to SPARQL editor

- src/app/main/mapper/iteration/iteration.component.ts
> GDB-4601 Fix doubling root triple when editing

- src/app/main/mapper/cell/cell.component.html
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/header/header.component.html
- src/app/main/mapper/header/header.component.ts
- src/app/main/mapper/mapper.component.html
- src/app/main/mapper/mapper.component.ts
- src/app/models/mapping-base.ts
- src/app/models/property-mapping-impl.ts
- src/app/models/simple-iri-value-mapping-impl.ts
- src/app/models/subject-mapping-impl.ts
- src/app/models/value-mapping-impl.ts
- src/app/services/model-management.service.ts
- src/app/services/rest/mapper.service.ts
- src/assets/i18n/en.json
Add call to the preview endpoint that return preview values incline in the MappingDefinition
Add preview attribute to MappingBase and show in mapper component
Remove the preview before saving and showing the MappingDefinition JSON
> GDB 4542 mapping preview

- src/app/app.module.ts
- src/app/main/components/components.module.ts
- src/app/main/components/dialog/dialog.component.html
- src/app/main/components/dialog/dialog.component.ts
- src/app/main/components/dialog/dialog.service.ts
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/header/header.component.ts
- src/app/main/mapper/iteration/iteration.component.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.spec.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/main/mapper/mapper.component.html
- src/app/main/mapper/mapper.component.ts
- src/assets/i18n/en.json
Provides conformation dialog when:
* deleting cell
* deleting root cell with all children
* deleting triple
* exit on dirty mapping cell
* browser navigation on not saved mapping
> GDB-4656 Provides dialog window service

- package-lock.json
- package.json
- src/app/main/mapper/iteration/iteration.component.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/services/rest/repository.service.spec.ts
- src/app/services/rest/repository.service.ts
- src/app/utils/constants.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
- src/styles/partials/rdf-mapping.css
Autocomplete namespaces, types, predicates, IRIs from repository. 
Add to the mapping definition only used prefixes.
Automatically detect prefixes for constants and set as transformation.
> GDB-4653 Autocomplete constants from repository

- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/utils/constants.ts
Allow the empty prefix.
Autocomplete types and predicates from ontology
> GDB-4653 Allow empty prefix and autocomplete from ontology

- src/app/directives/directives.module.ts
- src/app/directives/tab.directive.ts
- src/app/main/mapper/cell/cell.component.html
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/iteration/iteration.component.html
- src/app/main/mapper/iteration/iteration.component.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/services/model-construct.service.spec.ts
- src/app/services/model-construct.service.ts
- src/app/services/model-management.service.ts
- src/app/services/tab.service.ts
- src/app/utils/constants.ts
Refactored mapper dialog component
Added new service taking care of creating new mappings
Added tab directive to properly select next mapping
> GDB-4668 Edit constant values inline

- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.spec.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/services/rest/mapper.service.ts
- src/assets/i18n/en.json
Call REST API to Preview a GREL expression when adding to expression, languageTransformation and dataTypeTransformation fields.
> GDB-4654 GREL preview

- src/app/main/mapper/header/header.component.html
- src/app/main/mapper/header/header.component.ts
- src/app/main/mapper/iteration/iteration.component.ts
- src/app/main/mapper/mapper.component.html
- src/app/main/mapper/mapper.component.ts
- src/app/services/channel-name.enum.ts
- src/app/services/message.service.spec.ts
- src/app/services/message.service.ts
Provides messaging service to communicate between components.
Save mapping button is disabled when mapping is pristine.
> GDB-4699 Message service and disable save button when pristine

- src/app/main/mapper/iteration/iteration.component.ts
Add namespaces obtained from autocompleted contanst to mapping namespaces
> GDB-4717 Add autocompleted namespaces to mapping

- src/app/app.component.spec.ts
- src/app/app.module.ts
- src/app/main/mapper/header/header.component.spec.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.spec.ts
- src/app/main/mapper/mapper.component.spec.ts
- src/app/services/error-reporter.service.ts
- src/app/services/model-construct.service.spec.ts
- src/app/services/model-management.service.spec.ts
- src/app/services/notification.service.ts
- src/app/services/rest/mapper.service.spec.ts
- src/app/services/rest/mapper.service.ts
- src/app/services/rest/mapping-definition.service.spec.ts
- src/app/services/rest/mapping-definition.service.ts
- src/app/services/rest/repository.service.spec.ts
- src/app/services/rest/repository.service.ts
- src/theme.scss
* Implemented NotificationService which wraps the material's snackbar component
* Implemented ErrorReporterService which is used to process errors and log them or show notifications
* Integrated error reporter service in rest services
* Added custom styles for the notifications
https://ontotext.atlassian.net/browse/GDB-4646
> GDB-4646 Show notifications on http error

- src/app/main/mapper/header/header.component.html
- src/app/main/mapper/header/header.component.scss
- src/app/main/mapper/mapper.component.html
- src/app/main/mapper/mapper.component.scss
https://ontotext.atlassian.net/browse/GDB-4722
> GDB-4722 Make the top header vertically fixed

- src/app/main/mapper/cell/cell.component.html
- src/app/main/mapper/header/header.component.html
- src/app/main/mapper/header/header.component.scss
- src/app/main/mapper/header/header.component.spec.ts
- src/app/main/mapper/header/header.component.ts
- src/app/main/mapper/iteration/iteration.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.spec.ts
- src/app/main/mapper/mapper.component.spec.ts
- src/app/main/mapper/mapper.module.ts
- src/assets/i18n/en.json
* Add tooltips on action elements
* Add save in progress indicator
* Removed obsolete .gitkeep file
https://ontotext.atlassian.net/browse/GDB-4661
> GDB-4661 Add tooltips and banners on action components and dialogs

- src/app/main/mapper/header/header.component.html
- src/app/main/mapper/header/header.component.spec.ts
- src/app/main/mapper/header/header.component.ts
- src/app/main/mapper/iteration/iteration.component.ts
- src/app/main/mapper/mapper.component.spec.ts
- src/app/main/mapper/mapper.component.ts
- src/app/main/mapper/mapper.module.ts
- src/app/services/channel-name.enum.ts
- src/app/services/model-management.service.ts
Toggle preview. Show preview while editing a mapping, but only when the mapping is complete (a triple is not missing a predicate or object)
> GDB-4669 Toggle show preview and update instantly

- src/app/main/mapper/mapper.component.html
- src/app/utils/constants.ts
- src/styles/partials/rdf-mapping.css
Add namespace value as tooltip and provide better mapping sample defaults
> Namespaces values as tooltips and better defaults

- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/main/mapper/mapper.component.scss
- src/app/main/mapper/sources/source.component.html
- src/app/models/triple.ts
- src/assets/i18n/en.json
* Resolve if currently edited cell is iri and has descendants in order to show notification bar.
* Decreased padding and margin of sources panel because they seem excessively big.
https://ontotext.atlassian.net/browse/GDB-4660
> GDB-4660 Notify when edited cell references another triple

- src/app/main/mapper/header/header.component.html
- src/app/main/mapper/header/header.component.scss
- src/app/main/mapper/mapper.component.scss
- src/app/main/mapper/sources/source.component.html
* Improvement that makes the header to take less vertical space
* Moved the content close to the header
* Add header background to prevent content to be visible behind it when scrolling
> Improve layout of the header and content positioning

- src/app/main/mapper/header/header.component.html
- src/app/main/mapper/header/header.component.scss
- src/app/main/mapper/mapper.component.html
- src/app/main/mapper/mapper.component.scss
- src/app/main/mapper/sources/source.component.html
- src/styles/partials/rdf-mapping.css
* Make buttons in header a bootstrap buttons
* Make the unsaved changes message stay on single line in order to make the layout more stable on lower resolutions
* Remove some paddings and margins - mostly vertical once
* Add media query breakpoints for the heading and for the content vertical offset in order to prevent overlapping when resolution is changed
> GDB-4655 Layout improvements

- src/app/main/mapper/iteration/iteration.component.html
- src/app/main/mapper/iteration/iteration.component.ts
Nesting is applicable when the subject is of type IRI.
https://ontotext.atlassian.net/browse/GDB-4731
> GDB-4731 Allow nesting

- cypress/fixtures/edit-mapping/generate-rdf-error
- cypress/fixtures/edit-mapping/generate-sparql-error
- cypress/fixtures/edit-mapping/load-columns-error
- cypress/fixtures/edit-mapping/load-mapping-error.json
- cypress/fixtures/edit-mapping/load-namespaces-error
- cypress/fixtures/edit-mapping/mapping-model.json
- cypress/fixtures/edit-mapping/save-mapping-success.json
- cypress/fixtures/empty-mapping-model.json
- cypress/fixtures/mapping-model.json
- cypress/steps/header-steps.ts
- cypress/steps/mapping-steps.ts
- cypress/support/index.ts
- cypress/test/delete-tripple.spec.ts
- cypress/test/edit-mapping.spec.ts
- cypress/utils/selectors/header-component.selectors.ts
- src/app/main/mapper/cell/cell.component.html
- src/app/main/mapper/header/header.component.html
- src/app/main/mapper/iteration/iteration.component.html
- src/app/services/error-reporter.service.ts
Some services has specific content type expectations e.g. a Blob expected by the one for the rdf generation and this results in error response returned as a Blob. This required more specific cases in the error resolution in order to extract all server errors.
https://ontotext.atlassian.net/browse/GDB-4646
> GDB-4646 Resolve server errors and show notification

- cypress/fixtures/nest-triples/mapping-model.json
- cypress/test/delete.spec.ts
- cypress/test/nest-triples.spec.ts
- src/app/main/mapper/cell/cell.component.html
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/iteration/iteration.component.html
- src/app/main/mapper/iteration/iteration.component.scss
- src/app/main/mapper/iteration/iteration.component.ts
- src/app/models/triple.ts
- src/styles/partials/rdf-mapping.css
* Implement logic to mark nesting groups
* Styling the mapping groups
* Implement test for the nesting
https://ontotext.atlassian.net/browse/GDB-4769
> GDB-4769 Nesting triples

- cypress/steps/mapping-steps.ts
- cypress/test/delete.spec.ts
- src/app/main/mapper/iteration/iteration.component.html
> GDB-4747 Delete incomplete nested triples

- cypress/fixtures/edit-mapping/autocomplete-response.json
- cypress/steps/edit-dialog-steps.ts
- cypress/steps/mapping-steps.ts
- cypress/test/edit-mapping.spec.ts
- cypress/utils/selectors/mapper-component.selectors.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
* For the subject we only check for the form validity
* Add a test
https://ontotext.atlassian.net/browse/GDB-4800
> GDB-4800 Fix edit dialog OK button condition

- cypress/steps/mapping-steps.ts
- cypress/test/delete.spec.ts
- src/app/models/value-mapping-impl.ts
* Prevent error when preview is cleared
* Add test
https://ontotext.atlassian.net/browse/GDB-4792
> GDB-4792 Fix error when object is deleted

- cypress/fixtures/en.json
- cypress/steps/edit-dialog-steps.ts
- cypress/steps/mapping-steps.ts
- cypress/test/delete.spec.ts
- src/app/main/mapper/cell/cell.component.html
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/iteration/iteration.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/assets/i18n/en.json
* Resolve if the deleted node has children and alter the warning message
* Add tests
https://ontotext.atlassian.net/browse/GDB-4767
> GDB-4767 Warn user when mapping with children is going to be deleted

- cypress/fixtures/add-siblings/mapping-model.json
- cypress/steps/mapping-steps.ts
- cypress/steps/prepare-steps.ts
- cypress/test/add-siblings.spec.ts
- cypress/test/nest-triples.spec.ts
- cypress/test/triple-ending.ts
- src/app/main/mapper/cell/cell.component.html
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/cell/configuration-and-preview-cell/configuration-and-preview-cell.component.html
- src/app/main/mapper/cell/configuration-and-preview-cell/configuration-and-preview-cell.component.ts
- src/app/main/mapper/cell/configuration-cell/configuration-cell.component.html
- src/app/main/mapper/cell/configuration-cell/configuration-cell.component.ts
- src/app/main/mapper/cell/empty-block/empty-block.component.ts
- src/app/main/mapper/cell/preview-cell/preview-cell.component.html
- src/app/main/mapper/cell/preview-cell/preview-cell.component.ts
- src/app/main/mapper/iteration/iteration.component.html
- src/app/main/mapper/iteration/iteration.component.ts
- src/app/models/triple.ts
- src/app/utils/constants.ts
- src/assets/i18n/en.json
- src/styles/partials/rdf-mapping.css
Add siblings from each cell after all shared predicates/objects siblings and their nested triples.
Focus the new added empty cell.
Add proper turtle like triple ending with dot, comma and column.
Add tests of the new functionality.
> GDB-4768-add-siblings

- cypress/fixtures/edit-mapping/iri-with-children-model-preview-response.json
- cypress/fixtures/edit-mapping/iri-with-children-model.json
- cypress/fixtures/en.json
- cypress/steps/edit-dialog-steps.ts
- cypress/steps/mapping-steps.ts
- cypress/test/edit-mapping.spec.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/assets/i18n/en.json
* Changed message
* Add test
https://ontotext.atlassian.net/browse/GDB-4770
> GDB-4770 extend the warning message on iri with children delete

- src/app/main/mapper/iteration/iteration.component.scss
- src/styles/partials/rdf-mapping.css
* Decrease vertical margin between triples
* Decrease border width
> Improve styling

- cypress/test/delete.spec.ts
- src/app/main/mapper/iteration/iteration.component.ts
* Check if the triple is incomplete and has only predicate, then delete it
* Extended tests to cover all scenarios
https://ontotext.atlassian.net/browse/GDB-4747
> GDB-4747 properly delete nested triple

- cypress/test/delete.spec.ts
- Maybe the incomplete stub for the namespaces request was the problem
> Try fixing delete object test

- cypress/steps/edit-dialog-steps.ts
- cypress/test/edit-mapping.spec.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
GREL preview should use the form values while you are editing a cell.
> GDB-4775 GREL preview should use the form values

- cypress/fixtures/create-mapping/all-types-mapping-model.json
- cypress/steps/mapping-steps.ts
- cypress/test/create-mapping.spec.ts
- cypress/test/main/mapper/header-component.spec.ts
- cypress/test/main/mapper/mapper-component.spec.ts
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/cell/cell.module.ts
- src/app/main/mapper/cell/configuration-and-preview-cell/configuration-and-preview-cell.component.html
- src/app/main/mapper/cell/configuration-cell/configuration-cell.component.html
- src/app/main/mapper/cell/preview-cell/preview-cell.component.html
- src/app/main/mapper/cell/type-badge/type-badge.component.html
- src/app/main/mapper/cell/type-badge/type-badge.component.ts
- src/styles/partials/rdf-mapping.css
* Extract component for visualizing the type badge and reused in all cell views
* Add test
* Some minor cleanup
https://ontotext.atlassian.net/browse/GDB-4823
> GDB-4823 Display types in a badge inside the cell

- cypress/fixtures/delete/object-in-nested-triple-mapping-model.json
- cypress/test/delete.spec.ts
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/cell/empty-block/empty-block.component.ts
- src/app/main/mapper/iteration/iteration.component.ts
* Add proper check before property access
* Add test
https://ontotext.atlassian.net/browse/GDB-4822
> GDB-4822 delete object in nested triple

- src/app/main/mapper/iteration/iteration.component.ts
https://ontotext.atlassian.net/browse/GDB-4831
> GDB-4831 Prevent console errors when cancel mapping edit

- cypress/test/delete.spec.ts
- cypress/test/main/mapper/mapper-component.spec.ts
- src/app/main/mapper/iteration/iteration.component.ts
https://ontotext.atlassian.net/browse/GDB-4827
> GDB-4827 Add empty triples row when mapping is complete

- src/app/app.module.ts
- src/app/auth/token.interceptor.ts
- src/app/services/rest/repository.service.ts
- src/app/services/rest/rest.service.ts
Add TokenInterceptor that gets the Auth token from the cookies and set it on as Authorization header on each request
> GDB-4747 Add TokenInterceptor to send Authorization header

- cypress/fixtures/create-mapping/edit-mapping-namespace-response.json
- cypress/steps/edit-dialog-steps.ts
- cypress/test/create-mapping.spec.ts
- cypress/test/main/mapper/mapper-component.spec.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
* Configure transformation on edit dialog open and on type change
* Reset the transformation button selection status and expression fields on type change to prevent creation of wrong mapping by mistake
* Add tests
https://ontotext.atlassian.net/browse/GDB-4834
> GDB-4834 dynamically change transformations based on type

- cypress/fixtures/en.json
- cypress/test/edit-mapping.spec.ts
- src/app/main/mapper/cell/empty-block/empty-block.component.ts
- src/assets/i18n/en.json
Show an error if you try to set as a prefix transformation a prefix that is not known by the model or in the repo
> GDB-4837 Show error on unknown prefix set

- cypress/fixtures/delete/triple-with-children-mapping-model.json
- cypress/test/delete.spec.ts
- src/app/main/mapper/iteration/iteration.component.ts
Additional: Fix setting of last row css class
https://ontotext.atlassian.net/browse/GDB-4826
> Gdb 4826 delete triple with children

- src/app/main/mapper/iteration/iteration.component.ts
- src/app/utils/constants.ts
Uses window messaging to communicate with parent iframe
https://ontotext.atlassian.net/browse/GDB-4848
related to https://gitlab.ontotext.com/graphdb-team/graphdb/-/merge_requests/1480 and https://github.com/Ontotext-AD/graphdb-workbench/pull/226
> GDB-4848 Provides mapper exit confirmation when unsaved changes

- cypress/steps/mapping-steps.ts
- cypress/test/autocomplete.spec.ts
- src/app/main/mapper/cell/empty-block/empty-block.component.html
- src/app/main/mapper/cell/empty-block/empty-block.component.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/services/rest/repository.service.ts
Autocomplete prefixes inline in the table
Autocomplete columns and indexes after a prefix is typed
Test the both scenarios
> GDB-4742 Autocomplete prefixes and columns after prefixes

- cypress/fixtures/en.json
- cypress/test/main/mapper/mapper-component.spec.ts
- cypress/utils/selectors/mapper-component.selectors.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/models/language.ts
- src/app/services/model-construct.service.ts
- src/assets/i18n/en.json
related to GDB-4856 As a user I want to tell the mapper that a column value is aleady an IRI
> GDB-4856 Mark value as raw IRI

- src/app/main/mapper/mapper-dialog/mapper-dialog.component.scss
Allow GREL preview to be scrolled vertically when it doesn't fit the window
> GDB-4851 scroll GREL preview vertically when need

- cypress/steps/mapping-steps.ts
- cypress/test/edit-mapping.spec.ts
- src/app/main/mapper/iteration/iteration.component.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/services/model-construct.service.ts
- src/app/utils/constants.ts
fixes GDB-4883 Cannot create a type mapping from the edit window
> GDB-4861 Treat rdf:type as type predicate

- src/app/models/value-mapping-impl.ts
related to https://ontotext.atlassian.net/browse/GDB-4911
> GDB-4911 Value type undefined check fix

- cypress/fixtures/apply-prefixes/autocomplete-response.json
- cypress/fixtures/apply-prefixes/datatype-literal-mapping-model.json
- cypress/fixtures/apply-prefixes/iri-mapping-model.json
- cypress/steps/edit-dialog-steps.ts
- cypress/test/apply-prefixes.spec.ts
- cypress/test/edit-mapping.spec.ts
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/cell/transformation-type-badge/transformation-type-badge.component.ts
- src/app/main/mapper/iteration/iteration.component.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
- src/app/main/mapper/mapper.component.ts
- src/app/models/mapping-definition-impl.ts
- src/app/models/namespaces.ts
- src/app/services/model-construct.service.ts
- src/app/services/model-management.service.ts
- src/app/services/namespace.service.ts
- src/app/services/rest/repository.service.ts
* Add namespaces type and a namespaces service collecting functions for working with the namespaces
* Apply namespace type and service's functions where needed
* Allow the empty prefix sign to be visible in the UI
* Add tests
Resolves:
https://ontotext.atlassian.net/browse/GDB-4836
https://ontotext.atlassian.net/browse/GDB-4869
> GDB-4836 support empty prefix

- src/app/services/namespace.service.ts
https://ontotext.atlassian.net/browse/GDB-4929
> GDB-4929 properly show the empy prefix in a tooltip

- cypress/README.md
- cypress/steps/edit-dialog-steps.ts
- cypress/test/mapping-dialog.spec.ts
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
Prefix field is set to readonly when RawIRI is present
Rename the mapper-component spec to mapping-dialog spec and introduce a spec to test the case
> GDB-4968 Readonly prefix field when RawIRI set

- src/app/main/mapper/cell/configuration-and-preview-cell/configuration-and-preview-cell.component.html
- src/app/main/mapper/cell/configuration-and-preview-cell/configuration-and-preview-cell.component.scss
- src/app/main/mapper/cell/configuration-cell/configuration-cell.component.html
- src/app/main/mapper/cell/configuration-cell/configuration-cell.component.scss
- src/app/main/mapper/mapper-dialog/mapper-dialog.component.ts
Fixes GDB-4976 Invalid mapping created when switching from prefix to GREL
Fixes minor badge view issues
> GDB-4975 Properly clear mapping properties when editing IRI

- src/app/main/mapper/mapper-dialog/mapper-dialog.component.html
- src/assets/i18n/en.json
Added hint about column name case sensitivity when using GREL
> GDB-5251 Add hint when using GREL expression

- cypress/fixtures/edit-mapping/preview-mapping-model.json
- cypress/fixtures/edit-mapping/preview-response.json
- cypress/test/edit-mapping.spec.ts
- src/app/main/mapper/cell/cell.component.html
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/cell/cell.module.ts
- src/app/main/mapper/cell/configuration-and-preview-cell/configuration-and-preview-cell.component.html
- src/app/main/mapper/cell/preview-cell/preview-cell.component.html
- src/app/main/mapper/iteration/iteration.component.html
If the cell contains an IRI, it is made a link to the resource in the DB
> GDB-4864 IRIs in preview to be links to resource

- cypress/steps/mapping-steps.ts
- cypress/test/autocomplete.spec.ts
- cypress/test/edit-mapping.spec.ts
Fixed problems with tests:
- Option from dropdown was not selected on click
- Input is sometimes blurred automatically after typing
> GDB-5372 Fixed flaky tests

- src/app/main/mapper/cell/empty-block/empty-block.component.ts
Fixed condition to skip getting IRI description when input starts with '@' or '$'
> GDB-4912 Fix autocomplete only on IRIs

- cypress/steps/mapping-steps.ts
- cypress/test/edit-mapping.spec.ts
- src/app/app.module.ts
- src/app/main/mapper/cell/cell.component.ts
- src/app/main/mapper/cell/configuration-and-preview-cell/configuration-and-preview-cell.component.html
- src/app/main/mapper/cell/preview-cell/preview-cell.component.html
- src/environments/environment.prod.ts
- src/environments/environment.ts
Added an APP_INITIALIZER to manually get graphdb url and set it as environment variable to construct correct urls for IRIs in preview
> GDB-4864 Fix IRI links urls in preview

- src/app/app.component.ts
- src/app/services/message-hanglers/language-message-handler.ts
- src/app/services/message-hanglers/message-handler.ts
- src/app/services/window-message-handling.service.ts
- src/app/utils/message-type.ts
Implemented service to handle massages posted from parent window
> GDB-5294 Implement window messaging service to receive language string

- CHANGELOG.md
- cypress/fixtures/amsterdam/amsterdam-model.json
- cypress/fixtures/apply-prefixes/datatype-literal-mapping-model.json
- cypress/fixtures/apply-prefixes/iri-mapping-model.json
- cypress/fixtures/create-mapping/all-types-mapping-model.json
- cypress/fixtures/create-mapping/transformation-types-mapping-model.json
- cypress/fixtures/delete/mapping-model.json
- cypress/fixtures/delete/object-in-nested-triple-mapping-model.json
- cypress/fixtures/delete/triple-with-children-mapping-model.json
- cypress/fixtures/download-mapping/mapping-model.json
- cypress/fixtures/edit-mapping/base-iri-mapping-model.json
- cypress/fixtures/edit-mapping/grel-expression-edit-mapping-model.json
- cypress/fixtures/edit-mapping/incomplete-mapping-model.json
- cypress/fixtures/edit-mapping/mapping-model-with-preview.json
- cypress/fixtures/edit-mapping/mapping-model.json
- cypress/fixtures/edit-mapping/prefix-autocomplete-mapping-model.json
- cypress/fixtures/header/mapping-model.json
- cypress/fixtures/mapping-model.json
- cypress/fixtures/namespaces/base-iri-mapping-model.json
- cypress/fixtures/namespaces/custom-namespace-mapping-model.json
- cypress/fixtures/nest-triples/mapping-model.json
- src/environments/environment.ts
Additionally:
- Started a changelog document
> OR-186: Changed the default OntoRefine server port to 7333
